test:
  redis_url: redis://redistogo:2eab8a676a981817ebafd929fb5210bd@hammerjaw.redistogo.com:11068/
  redis_pool_size: 5
development:
  redis_url: redis://redistogo:2eab8a676a981817ebafd929fb5210bd@hammerjaw.redistogo.com:11068/
  redis_pool_size: 5
production:
  redis_url: redis://redistogo:0ec33a6d36d9d4e488ed1288812a9cf1@sole.redistogo.com:10137/
  redis_pool_size: 10