test:
  adapter: postgresql
  database: nt_project_test
  host: 172.19.0.1
  port: 5432
  username: postgres
  password: 123456
  pool: 2

development:
  adapter: postgresql
  database: nt_project_dev
  host: 172.19.0.1
  port: 5432
  username: postgres
  password: 123456
  pool: 2

production:
  adapter: postgresql
  database: duli4kkh524dt
  host: ec2-54-209-221-231.compute-1.amazonaws.com
  port: 5432
  username: athfypvdoyalol
  password: 726cc50549d957793abe573cf54b2c3ea19ae6b181c8a7151826f95a8fc69674