test:
  adapter: postgresql
  database: nt_project_test
  host: 172.18.192.1
  port: 5432
  username: postgres
  password: 123456
  pool: 2

development:
  adapter: postgresql
  database: nt_project_dev
  host: 172.18.192.1
  port: 5432
  username: postgres
  password: 123456
  pool: 2

production:
  adapter: postgresql
  database: nt_project_prod
  host: 172.18.192.1
  port: 5432
  username: postgres
  password: 123456
  pool: 2