test:
  adapter: postgresql
  database: nt_project_test
  host: 172.19.0.1
  port: 5432
  username: postgres
  password: 123456
  pool: 2

development:
  adapter: postgresql
  database: nt_project_dev
  host: 172.19.0.1
  port: 5432
  username: postgres
  password: 123456
  pool: 2

production:
  adapter: postgresql
  database: df8nooibf3mp9g
  host: ec2-3-219-204-29.compute-1.amazonaws.com
  port: 5432
  username: lufmcxgqcfoarq
  password: 284a706a401cbac8aa64570506edd72115ab2d5889ad02ac5f31d38bafededef